services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    networks:
      - transaction-ledger-network

  # API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-ledger-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/transaction_ledger?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always
    networks:
      - transaction-ledger-network

volumes:
  mongodb_data:
    driver: local

networks:
  transaction-ledger-network:
    driver: bridge